name: docker-compose-actions-workflow
on: workflow_dispatch
jobs:
  test:
    env: # Or as an environment variable
      NAME: ${{ secrets.NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: curl http://localhost:80/
